name: Security audit

on:
  push:
    branches:
      - main
      - "renovate/*"
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

jobs:
  pre_job:
    permissions:
      actions: write
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 30
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@b974a9395958c231af965b70070979a577efa578 # v5.3.2
        with:
          paths: '["**/Cargo.toml", "**/Cargo.lock", ".github/workflows/security.yml"]'
          concurrent_skipping: same_content
          do_not_skip: '["release", "workflow_dispatch", "schedule"]'
          skip_after_successful_duplicate: true

  security_audit:
    permissions:
      contents: read
      issues: write
      checks: write
      security-events: write
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
        with:
          install: false
      - name: Ensure Rust toolchain and components are installed
        run: mise install --force rust
      - name: Add a job summary
        run: mise exec aqua:rustsec/rustsec/cargo-audit -c "cargo audit >>$GITHUB_STEP_SUMMARY 2>&1 || true"
      - run: mise exec aqua:rustsec/rustsec/cargo-audit -c "cargo audit --format sarif >cargo-audit.sarif"
      - uses: github/codeql-action/upload-sarif@1c5b675653bb5c22dbe9b12b556ec555138e09fd # v4.38.1
        if: always()
        with:
          sarif_file: cargo-audit.sarif
